### ISSUE TITLE
Accessing Command History Takes Two Keypresses

### ISSUE THREAD

**Issue by Trinnith** [EmpyrealHell/wolfpack-rpg-client#12]
Version: 1.0.3
Behavior: When using the up arrow key to access previously issued commands, two up arrow key presses are required to view the most recently issued command
Expected Behavior: The previously issued command should populate the command prompt after one up arrow key press

Repro Steps:
1. Open the application fresh or refresh the page
2. Issue a valid command (in this case, I used "!pets") and wait for lobot's response
3. Press the up arrow key, notice that no command is populated in the prompt
4. Hit the up arrow key again, and find that the command is now shown

**Comment by EmpyrealHell** [comment]
I'll push another release tonight that includes this fix
