### ISSUE TITLE
Unable to Queue

### ISSUE THREAD

**Issue by The-Harpoon** [EmpyrealHell/wolfpack-rpg-client#20]
I've not be able to queue in to any dungeons. When inputting the command '!queue' nothing happens afterwards as seen in screenshot 'Queue_Commands.JPG'. 
I am able to use some other commands though such as '!stats', '!xp', '!inventory', '!pets' as seen on the other attached screenshots.

Quite a while back I changed my twitch name from 'the_harpoon21' to 'the_harpoon' which meant I lost my profile, however yesterday (July 28th) Lobos sorted that out for me. But I'm not able to queue up (and did lose Inventory + pets).
This queuing occurs both within twitch whispers as well as the WolfPack client.
Using Desktop, and the latest version of Google Chrome

Please let me know if you need any other info/screenshots.
![Queue_Commands](https://user-images.githubusercontent.com/6407460/88840298-29a25d80-d1d4-11ea-9157-29f963a16b83.JPG)

![Inv_Pets_Commands](https://user-images.githubusercontent.com/6407460/88840296-2909c700-d1d4-11ea-807e-aa7181bcc040.JPG)

![Stats_xp_commands](https://user-images.githubusercontent.com/6407460/88840300-29a25d80-d1d4-11ea-84c8-2eeba92b8c56.JPG)

![Chrome_Dev_Tools_Green](https://user-images.githubusercontent.com/6407460/88841246-936f3700-d1d5-11ea-9481-81d5c25f3f49.JPG)

**Comment by EmpyrealHell** [comment]
Wow, I completely missed this, I'm so sorry! Unfortunately, if you can communicate with the bot at all, then the issue isn't with the website but with the bot. You'll have to talk to Lobos about that, or post a bug on the lobot github page ([https://github.com/lobosjr/lobotjr/issues](https://github.com/lobosjr/lobotjr/issues))
