### ISSUE TITLE
Fishing Tournament Results Spam

### ISSUE THREAD

**Issue by gleebeard** [EmpyrealHell/wolfpack-rpg-client#28]
In v2.0.0, whenever a command is issued into the console, it repeats the winner of the most recent fishing tournament alongside the actual contents of the command itself. I've attached a screenshot of the console.

![Results spam](https://user-images.githubusercontent.com/71455656/105232862-420d8800-5b26-11eb-986a-f81f24603916.PNG)

**Comment by EmpyrealHell** [comment]
I'm not sure if it's actually resending the command or just reprinting it. I will try and look into this today to try and figure out which. Thanks!

**Comment by EmpyrealHell** [comment]
This has been resolved in update 2.1.2
