### ISSUE TITLE
Fishing tournament Wolfpack RPG Client issue

### ISSUE THREAD

**Issue by LeSpou7nik** [EmpyrealHell/wolfpack-rpg-client#48]
I don't know if it is a bug but while in fishing tournament got a line that went 

Trout | 98 | 17.65 (--0.05999999999999872) | 20.55 (--1.8599999999999994) |

Have a nice one !

**Comment by EmpyrealHell** [comment]
Any message that shows up in the console with pipes separating different values is normal. These messages are sent by the bot in this compact format to get more information to the client in fewer messages to reduce the load on the bot. As long as it's not causing any issues with how the fishing tournaments work you can just ignore messages like that.
