### ISSUE TITLE
Fishing tournament results incorrect

### ISSUE THREAD

**Issue by ashufelt** [EmpyrealHell/wolfpack-rpg-client#61]
I got 2004 points in a fishing tournament, and placed 2nd. The winner was listed as getting 1624 points.  

![fishingResults](https://user-images.githubusercontent.com/18423607/183216909-c1bc017c-aa5b-4edc-b68f-7efd230986eb.PNG)  
![fishingResults2](https://user-images.githubusercontent.com/18423607/183216927-c32ed377-092b-49c8-81d6-46d1d542d518.PNG)

Other possibly relevant details:
I participated entirely on the Wolfpack RPG Client, by clicking the button in the Fishing UI.

**Comment by EmpyrealHell** [comment]
Well that's no good. I think I know what might be causing it, and why our tests didn't catch it. I'll look into it in more detail tomorrow and get back to you.
