### ISSUE TITLE
Stuck at checking access an never continues.

### ISSUE THREAD

**Issue by Lilmacaco** [EmpyrealHell/wolfpack-rpg-client#78]
Whenever I launch the fishing tournament it just gets stuck on check access no matter how long I wait. See attached screenshots and logs.

![WolfPackFishingError](https://github.com/EmpyrealHell/wolfpack-rpg-client/assets/6832714/62d3424e-b2c9-4da1-ac55-3529946c5577)
[WebConsoleErrorLog.txt](https://github.com/EmpyrealHell/wolfpack-rpg-client/files/14672464/WebConsoleErrorLog.txt)

**Comment by EmpyrealHell** [comment]
From the error log it looks like your account doesn't have a verified phone number attached. I believe this is a requirement to send whispers through a 3rd-party client. Can you check whether you have a verified phone number?

**Comment by Lilmacaco** [comment]
> From the error log it looks like your account doesn't have a verified phone number attached. I believe this is a requirement to send whispers through a 3rd-party client. Can you check whether you have a verified phone number?

It would seem you are correct. I am adding the phone number now and everything is working.
