### ISSUE TITLE
Issue executing commands in WolfpackRPG

### ISSUE THREAD

**Issue by armitak1** [EmpyrealHell/wolfpack-rpg-client#79]
**Console Output**

GET
https://empyrealhell.github.io/wolfpack-rpg-client/play
[HTTP/2 404  18ms]

[12:01] error: Could not connect to server. Reconnecting in 1 seconds.. main.b55b20fc24d3ade0.js:1:166795
GET
https://empyrealhell.github.io/assets/apple-touch-icon.png
[HTTP/2 404  0ms]

GET
https://empyrealhell.github.io/assets/favicon-16x16.png
[HTTP/2 404  0ms]

XHROPTIONS
https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=0,168,19194,19938,20076,21383,21996,25684,25685,76131,163459,300374282,333885163,335835868,371053293,398318760,453493635,453642585,488737509,610186276,265a4640-87df-4086-88f9-49369d237449,36237fd7-c0b9-49d7-8731-89cc902c3091,44cdaec3-1d7d-4edf-889d-64968e8f32c2,a4e7a808-d15a-4b82-9e6f-fe72f411b6ef,a529ca50-d1ed-42d9-b9b0-063986321ed8
CORS Missing Allow Origin

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=0,168,19194,19938,20076,21383,21996,25684,25685,76131,163459,300374282,333885163,335835868,371053293,398318760,453493635,453642585,488737509,610186276,265a4640-87df-4086-88f9-49369d237449,36237fd7-c0b9-49d7-8731-89cc902c3091,44cdaec3-1d7d-4edf-889d-64968e8f32c2,a4e7a808-d15a-4b82-9e6f-fe72f411b6ef,a529ca50-d1ed-42d9-b9b0-063986321ed8. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 410.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=0,168,19194,19938,20076,21383,21996,25684,25685,76131,163459,300374282,333885163,335835868,371053293,398318760,453493635,453642585,488737509,610186276,265a4640-87df-4086-88f9-49369d237449,36237fd7-c0b9-49d7-8731-89cc902c3091,44cdaec3-1d7d-4edf-889d-64968e8f32c2,a4e7a808-d15a-4b82-9e6f-fe72f411b6ef,a529ca50-d1ed-42d9-b9b0-063986321ed8. (Reason: CORS request did not succeed). Status code: (null).
XHROPTIONS
https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=0,168,19194,19938,20076,21383,21996,25684,25685,76131,163459,300374282,333885163,335835868,371053293,398318760,453493635,453642585,488737509,610186276,265a4640-87df-4086-88f9-49369d237449,36237fd7-c0b9-49d7-8731-89cc902c3091,44cdaec3-1d7d-4edf-889d-64968e8f32c2,a4e7a808-d15a-4b82-9e6f-fe72f411b6ef,a4e7a808-d15a-4b82-9e6f-fe72f411b6ef,a529ca50-d1ed-42d9-b9b0-063986321ed8
CORS Missing Allow Origin

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=0,168,19194,19938,20076,21383,21996,25684,25685,76131,163459,300374282,333885163,335835868,371053293,398318760,453493635,453642585,488737509,610186276,265a4640-87df-4086-88f9-49369d237449,36237fd7-c0b9-49d7-8731-89cc902c3091,44cdaec3-1d7d-4edf-889d-64968e8f32c2,a4e7a808-d15a-4b82-9e6f-fe72f411b6ef,a4e7a808-d15a-4b82-9e6f-fe72f411b6ef,a529ca50-d1ed-42d9-b9b0-063986321ed8. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 410.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=0,168,19194,19938,20076,21383,21996,25684,25685,76131,163459,300374282,333885163,335835868,371053293,398318760,453493635,453642585,488737509,610186276,265a4640-87df-4086-88f9-49369d237449,36237fd7-c0b9-49d7-8731-89cc902c3091,44cdaec3-1d7d-4edf-889d-64968e8f32c2,a4e7a808-d15a-4b82-9e6f-fe72f411b6ef,a4e7a808-d15a-4b82-9e6f-fe72f411b6ef,a529ca50-d1ed-42d9-b9b0-063986321ed8. (Reason: CORS request did not succeed). Status code: (null).
Storage access automatically granted for origin “https://github.com” on “https://empyrealhell.github.io”.
XHROPTIONS
https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=undefined
CORS Missing Allow Origin

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=undefined. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 410.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=undefined. (Reason: CORS request did not succeed). Status code: (null).
XHROPTIONS
https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=undefined
CORS Missing Allow Origin

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=undefined. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 410.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=undefined. (Reason: CORS request did not succeed). Status code: (null).

Network Log

[wolfpackRPGnetworkLog.txt](https://github.com/EmpyrealHell/wolfpack-rpg-client/files/14727494/wolfpackRPGnetworkLog.txt)

**Comment by EmpyrealHell** [comment]
There was an issue with the internal state of the database. That should be resolved now, so please try again and let me know if it works. Thanks!
